### ISSUE TITLE
Add wrapper to cast double into int and print warnings in PDE console

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#108]
Now we have some dirty code: `as.integer()` in R, it is not cool

**Comment by jeremydouglass** [comment]
Good approach adding these casts to the mappings in BuiltinApplet.java

Question: This issue included "and print warnings in PDE console." What was that about? This is closed by #155, which doesn't seem to do anything regarding warnings and the console.

**Comment by jeremydouglass** [comment]
I'm on the fence about whether console warning are important in this case.

On the one hand, functions like colorMode(mode) are supposed to be passed a built-in keyword constants, like `RGB`, which corresponds to an ints. If you are passing colorMode something like "1.234" then something has probably gone really wrong and the user should probably know.

On the other hand, if we cast and it works, it works. Not checking is the simpler implementation. It is also slightly faster to not check -- especially in rare cases where a mode is being set in the draw loop. In those cases we would also be flooding the console with the same error.

What do you think?

**Comment by gaocegege** [comment]
colorMode is a special function, I didn't do the cast work in colorMode because there are already a function `colorMode(float gray)`.

And duplicate warnings are annoying, maybe we could output warnings in PDE's DEBUG level log?

**Comment by jeremydouglass** [comment]
Wait, didn't you do a colorMode cast right here on line 49?

https://github.com/gaocegege/Processing.R/pull/155/files#diff-1b622df5eb779e08b4da702d9749b874R49

**Comment by gaocegege** [comment]
Sorry, my mistake. I mean `background`

= = It's a little confusing

**Comment by jeremydouglass** [comment]
I agree that DEBUG level makes sense.

I know what you mean about the background keyword. :) `colorMode()` sets the color space and range (RGB, HSB, etc.) for all color related drawing commands like fill(), stroke(), background(). `background()` paints the whole sketch canvas with a single color.

While we are looking at this, here is a quick rundown of potentially relevant entries from the Processing(Java) reference that take a specially defined int as an one of the arguments.

- Anything named "mode":
  - blendMode()
  - colorMode()
  - ellipseMode()
  - imageMode()
  - rectMode()
  - shapeMode()
  - textureMode()
  - textMode()
- Other configuration-setting functions:
  - pixelDensity()
  - strokeCap()
  - strokeJoin()
  - textureWrap()
- "detail" functions, which take a pure int (not a keyword constant):
  - bezierDetail()
  - curveDetail()
  - noiseDetail()
  - sphereDetail()
- frameCount -- not a function, but it must be an set to an int when updated. There is no such thing as draw frame 1.5.

**Comment by gaocegege** [comment]
Thanks, the list works for me!

I have to go to bed now 🤔 Plz leave comments if there is something we need to talk about and I will reply tomorrow.

**Comment by jeremydouglass** [comment]
I see that the merged PR #162 adds warnings for `size()`, `bezierDetail()`, and `colorMode()`.

Was there any reason not to add warnings for all the other items in the list above? Why `bezierDetail()` but not `curveDetail()`?

**Comment by gaocegege** [comment]
Done in https://github.com/gaocegege/Processing.R/pull/182/commits/2f1f8658301ff197a4e384163422cfec2fb617fb

**Comment by jeremydouglass** [comment]
I can see that https://github.com/gaocegege/Processing.R/pull/182/commits/2f1f8658301ff197a4e384163422cfec2fb617fb adds support for all the detail functions.

Are the other casts to int from double to int done as well, or should a separate issue be created for them? From the list above:

- Anything named "mode":
  - blendMode()
  - colorMode()
  - ellipseMode()
  - imageMode()
  - rectMode()
  - shapeMode()
  - textureMode()
  - textMode()
-  Other configuration-setting functions:
  - pixelDensity()
  - strokeCap()
  - strokeJoin()
  - textureWrap()

**Comment by gaocegege** [comment]
I will file a new issue. Thanks for your information
