### ISSUE TITLE
Fix ad-hoc examples in documentation

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#110]
There are some examples in documentation that can not be implemented now:

- [x] resetMatrix: Can not reproduce the image: https://processing.org/reference/resetMatrix_.html
- [x] sphereDetail: No mouseY now
- [x] texture: No matching function
- [x] textureMode: No matching function
- [x] printProjection: No picture but we should have in design
- [x] printCamera: No picture but we should have in design
- [x] screenX: object 'mouseX' not found
- [x] screenY: object 'mouseX' not found
- [x] screenZ: object 'mouseX' not found
- [x] printMatrix: No picture but we should have in design
- [x] rotateX/Y/Z 1: No radians function

**Comment by gaocegege** [comment]
I think the resetMatrix is broken in https://processing.org/reference/resetMatrix_.html

**Comment by jeremydouglass** [comment]
I agree -- it looks like they may have simplified the example at some point but never fixed the reference image. Would you like to submit an issue to processing docs?

Solution: generate our own image in Java mode based on the Java reference example code +saveFrame(), use that as the reference in our e2e. You can submit it in a pull to -docs as well if you like, or just use it locally.

https://github.com/processing/processing-docs/issues

Are there others that are still broken?

**Comment by gaocegege** [comment]
OK, I will submit the issue :)

**Comment by gaocegege** [comment]
https://github.com/processing/processing-docs/issues/593

It is not our issue so I will add the example and close it.
