### ISSUE TITLE
Layout error in documentation

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#112]
![image](https://user-images.githubusercontent.com/5100735/27021853-9d5842b2-4f7d-11e7-83c1-b1d14c6de2aa.png)

**Comment by jeremydouglass** [comment]
Is this a bug in Processing.R-docs, or here, and is style.css a generated file normal?

In `style.css`:

Fix description width from:

    .example { clear: both; margin-bottom: 15px; }

to:

    .example { clear: both; margin-bottom: 15px; width:600px; }

Also, optionally hide long code lines inside a scrollbox (or maybe not necessary, leave it and just let them run over). From:

    .example pre.margin { margin-left: 115px; }

to:

    .example pre.margin { margin-left: 115px; overflow:scroll; }

**Comment by gaocegege** [comment]
I think it is a bug in Processing.R-docs but it is better to put all issues in this repo, IMO.

**Comment by jeremydouglass** [comment]
To make project management simpler for GSOC the it is fine to have all bugs in this repo.

*After* GSOC is over and the handoff happens: any known docs bugs like this should probably be migrated to the docs repo and closed here.

**Comment by jeremydouglass** [comment]
https://github.com/Processing-R/Processing.R-docs/pull/1
