### ISSUE TITLE
reference: Can't show functions which have no subcategory

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#117]
![image](https://user-images.githubusercontent.com/5100735/27077884-2c7ddad8-5064-11e7-8fe9-5cf5fa1f1bf7.png)

We have some functions in Environment directly but it does not be shown.

**Comment by gaocegege** [comment]
It may be caused by https://github.com/Processing-R/Processing.R-docs/blob/master/src/generate.py#L47

**Comment by gaocegege** [comment]
Close via https://github.com/Processing-R/Processing.R-docs/commit/7b392af9385a6c368ab48c34320dc41342d88c81

**Comment by jeremydouglass** [comment]
These more complete lists of entries combined with the width css fix on individual pages are all looking very good!
