### ISSUE TITLE
Write a tech report to introduce the architecture of Processing.R

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#119]
Now I have invited some friends of me to contribute to Processing.R, so we need a article to illustrate the architecture of Processing.R to help them get started

**Comment by jeremydouglass** [comment]
Good idea. What is a specific example of a previous architecture tech report that you would see as a model for this one?

Would this report be hosted?

1. as a .md file in this repo?
2. as a github wiki page with the repo?
3. as a web page in the processing.r-docs repo /  on https://processing-r.github.io/Processing.R-docs/ ?

**Comment by gaocegege** [comment]
I think it is better to put it as a markdown file in this repo, since the documentation is only needed by contributors.
