### ISSUE TITLE
Replace ant with maven or gradle

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#139]
Now Processing.R uses maven-ant-tasks to install maven dependencies in ant. If we could use maven instead, it may be better.

**Comment by jeremydouglass** [comment]
It might be be worth searching Processing issues for maven and then checking with core developers on whether the main code base also has similar plans to change build systems. Whether they do or not might not matter, or you could learn something interesting.

**Comment by jeremydouglass** [comment]
Perhaps this should be closed wontfix? It could be reopened in the future if Processing(Java) retools its own build process and it makes sense to do the same with the mode.

**Comment by gaocegege** [comment]
Yeah, it is a good idea.
