### ISSUE TITLE
renjin: Unable to build in x86 architecture

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#140]
One of the dependency of renjin, `gcc-bridge-plugin-linux-x86_64.jar`, doesn't have x86 version.

**Comment by gaocegege** [comment]
I will setup a x86 environment and test if the mode works well. If it works, then there is no need to build the mode in x86.

**Comment by jeremydouglass** [comment]
1. Have you asked on the renjin list about this -- specifically about how hard it would be to get a gcc-bridge-plugin-linux-x86_64.jar ?

2. Is this dependency only affecting the AppVeyor(Windows) CI target? For example, I know that I just looked and the last three PRs #138 #144 #145  have had strange CI results -- fails and timeouts in both AppVeyor and Travis.

**Comment by gaocegege** [comment]
1. I haven't, and I will ask in a few days.
2. The last three PRs failed because I merged the PR before the CI finished.

**Comment by gaocegege** [comment]
Now build in x86 will use the jars in lib, build in x64 will download jars from remote and move the jars to lib.
