### ISSUE TITLE
Welcome to have a try on Processing.R

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#142]
Processing.R has released 5 versions. You can get the latest mode from [Release Page](https://github.com/gaocegege/Processing.R/releases).

After you download the mode, place it into Processing "modes" directory:

-  macOS: `${HOME}/Documents/Processing/modes`
-  Linux: `${HOME}/sketchbook/modes`
- Windows: `C:\Users\<user>\Documents\Processing\modes`

Now the features in Processing.R include:

### Built-in functions in Processing

The documentation website is [https://processing-r.github.io/Processing.R-docs/](https://processing-r.github.io/Processing.R-docs/). This documentation is currently incomplete. Most Processing functions are theoretically supported in Processing.R, but many functions have not been tested and some pages have not been edited yet to reflect differences from other Processing modes.

### Libraries in Processing: `importLibrary()`

Processing.R supports importing standard Processing(Java) libraries that enrich the functionality of Processing. The function `importLibrary()` imports new libraries manually. This has been tested with one library: [peasycam](http://mrfeinberg.com/peasycam/), the "dead-simple mouse-driven camera for Processing."

Before trying the example code below, first install the corresponding library `peasycam` -- for example using the PDE Contribution Manager > Library.

```r
settings <- function() {
    importLibrary("peasycam")
    size(200, 200, P3D)
}

setup <- function() {
    cam = PeasyCam$new(processing, 100)
    cam$setMinimumDistance(50)
    cam$setMaximumDistance(500)
}

draw <- function() {
    rotateX(-.5)
    rotateY(-.5)
    background(0)
    fill(255, 0, 0)
    box(30)
    pushMatrix()
    translate(0, 0, 20)
    fill(0, 0, 255)
    box(5)
    popMatrix()
}
```

### R Packages: `library()`

Processing.R has limited support for R packages. It will automatically download R packages that are requested using the `library()` function, so you can use packages directly.

Here is an example using the `foreach` package:

```r
library(foreach)

foreach(i=1:3) %do%
    print(sqrt(i))
```

In practice we have only found a few R packages so far that work with Processing.R "out of the box." This is because the package must be pure R  **and** all of its dependencies must also be pure R. There is [renjin list of R packages](http://packages.renjin.org/) which lists their compatibility with the renjin JVM. Any package fully supported in renjin is theoretically supported in Processing.R.

## Limitations in Processing.R

Processing.R is in active development as an experimental pre-release version.

**Static sketches:** Processing.R does not have a good support for detecting static/active/mix mode. We recommend that all sketches be written in full active mode, defining a separate `settings`, `setup` and `draw`. Even simple sketches should be wrapped in `draw()`. For example, do not write:

```R
line(0, 10, 90, 100)
```

That may cause bugs. Instead, write:

```R
draw <- function() {
    line(0, 10, 90, 100)
}
```

Please try our experimental mode and give us your feedback :) If you want to contribute to this mode, there are [issues for new contributors](https://github.com/gaocegege/Processing.R/issues?q=is%3Aissue+is%3Aopen+label%3Afor-new-contributors) and the [architecture documentation](https://github.com/gaocegege/Processing.R/blob/master/raw-docs/architecture.md).

If you have any problem about the mode, come chat at the [Processing.R gitter channel](https://gitter.im/gaocegege/Processing.R) :tada:

**Comment by Dinoswarleafs** [comment]
So excited :D!

**Comment by kfrajer** [comment]
Can P.R run under Windows? If it doesn't, would it be possible in the future?

Kf

**Comment by gaocegege** [comment]
I haven't test now. I will have a try today or tomorrow :smile:

**Comment by kfrajer** [comment]
@gaocegege Let me know if you want me to give it a try from my side. I am not sure what file I should get. I have R and P3.3.5 already on my machine and I am looking forward to go through the steps to get the mode running in my Win10 machine. 

Kf

**Comment by gaocegege** [comment]
![image](https://user-images.githubusercontent.com/5100735/28149374-ba3a49c0-67bf-11e7-8aff-585bd571eb81.png)

Hi, kf

I have tried to run 2D sketches in Win 10 Virtual Machine. It works.

If you want to have a try, download the [releases/download/v1.0.4-alpha/RLangMode.tar.gz](https://github.com/gaocegege/Processing.R/releases/download/v1.0.4-alpha/RLangMode.tar.gz) from release page and put the mode into `c://users/<users>/Documens/Processing/modes`.

**Comment by kfrajer** [comment]
Could I download a branch from git. I don't have access to tar.gz files in Win10.

Kf

**Comment by gaocegege** [comment]
Does zip works for you? I have uploaded a zip file with same content: https://github.com/gaocegege/Processing.R/releases/download/v1.0.4-alpha/RLangMode.zip

**Comment by kfrajer** [comment]
Thank you. The zip worked. I got the R mode running but I cannot get it to run. I use the example above and I removed all references to peasycam just to keep it simple.

Kf

**Comment by gaocegege** [comment]
peasycam is in Library's example, you could have a try in Basics's example, for example, https://github.com/gaocegege/Processing.R/blob/master/examples/Basics/BasicOperations/BasicOperations.rpde

**Comment by kfrajer** [comment]
Hmmm... Nothing happens... no sketch, no error trace... I can try more tomorrow. 

Kf

**Comment by gaocegege** [comment]
:thinking: 

Yeah, P.R now doesn't output errors in PDE console, I will have a try when I return home tonight. It is weird

**Comment by gaocegege** [comment]
I don't meet any problem 🤔 Maybe you could start from a simple sketch: `line(0,10,10,0)` or something else.

**Comment by kfrajer** [comment]
@gaocegege Really odd. Nothing even using simple line examples. Let me ask, do I need to setup R in any way?

**Comment by gaocegege** [comment]
No, R is just a java dependency in the mode, so it is built-in. Could I get your Version of Processing?

**Comment by kfrajer** [comment]
P3.3.5 64bit

**Comment by gaocegege** [comment]
It is same as mine. Could you start PDE in console and set an environment variable `VERBOSE_RLANG_MODE=true`:

```
VERBOSE_RLANG_MODE=true <PATH_TO_PDE>
```

It will output the logs of Processing.R in the console.

**Comment by kfrajer** [comment]
So this is what I did. Starting at the processing.exe location, I issued: `set VERBOSE_RLANG_MODE=true` and then I started processing from the command prompt. Nothing happened. This is what I issued:

`processing-java --sketch=%cd%/sketch_170715a --run`

Now from what I know, the sketch name in the previous line corresponds to the name of the folder. The name of the file has an extension **rpde** so I encountered this next error: 

> Not a valid sketch folder. C:\Users\C\AppData\Local\Temp\untitled6502517713539763193sketches\sketch_170715a\sketch_170715a.pde does not exist.

I am thinking maybe you want me to do something else? Or am I missing something, as for example, how to handle *rpde* files via command prompt.

Kf

**Comment by gaocegege** [comment]
Hi, it is my mistake. I want to get the log of PDE, and I tried to follow the code https://github.com/processing/processing/blob/processing-0262-3.3.5/app/src/processing/app/Base.java#L153 add a `debug.txt` in APPDATA/roaming/processing, but it doesn't work. Then add VERBOSE_RLANG_MODE will not work.

processing-java could not run rpde, only PDE's R mode could. I am trying to make Processing in Windows output logs for PDE. My PDE is clean and does not have any other mode or library, maybe you could back up the libraries and modes, then make a clean environment and have another try :thinking: 

Sorry for the bad experience with Processing.R in Windows, again :pray:

**Comment by kfrajer** [comment]
So I remove my sketch folder and removed the preferences folder (renamed them) and then I ran processing and allowed it to create the default folders. I closed it and then I moved the R mode right into the *modes* folder. I created the debug.txt file in the new preference folder and run Processing in R mode and all the same. I am thinking the debugging option needs to be enabled:

https://github.com/processing/processing/blob/processing-0262-3.3.5/app/src/processing/app/Base.java#L64

> /**
>    * True if heavy debugging error/log messages are enabled. Set to true
>    * if an empty file named 'debug' is found in the settings folder.
>    * See implementation in createAndShowGUI().
>    */


On a side note, you said:

> My PDE is clean and does not have any other mode or library

Just to clarify, you have the java mode still available there, right? 

Kf

**Comment by gaocegege** [comment]
Yeah, java is built-in and available in my Windows environment

**Comment by gaocegege** [comment]
![image](https://user-images.githubusercontent.com/5100735/29118652-73174b84-7d35-11e7-8148-7388e8e28ddb.png)

I have a Windows laptop now and it works well 🤔

**Comment by jeremydouglass** [comment]
Great! @kfrajer, please try again with the latest release -- or wait a few days and it will be available in PDE > Contributions Manager > Modes.

**Comment by kfrajer** [comment]
@gaocegege @jeremydouglass   I confirmed the R mode works in my machine. See below.

I also ran the provided example **RPackageBasics.rpde** and it took a while to execute because it was downloading the library. I have R in my computer. Is it possible to tell the R mode to check my current installed libraries under my R stand-alone version?  It would be great to have a single pool for the libraries. It is not a deal breaker, and it is really not that important... it is more of a thought.

Now I am interested to see more about how I can integrate R and P3 together. Do you have more examples available? Is there more examples available in the R Mode's reference?

Kf

![rmode](https://user-images.githubusercontent.com/26076840/29249855-9d1aad6a-7ff4-11e7-9e3f-222de04831cc.png)

**Comment by gaocegege** [comment]
It is good news. There are lots of examples available in ``File -> Examples`

<img width="960" alt="2017-08-14 4" src="https://user-images.githubusercontent.com/5100735/29256645-8f2aff44-80de-11e7-8a21-eea06a772ec5.png">

<img width="960" alt="2017-08-14 5" src="https://user-images.githubusercontent.com/5100735/29256659-a21cf31e-80de-11e7-9bdd-bb2f0ea6f622.png">

**Comment by jeremydouglass** [comment]
Great news, @kfrajer. If you have ideas and feedback about types of R integration, please share them!

**Comment by kfrajer** [comment]
Great to see the examples. For some reason I just checked the one that was related to R. I will check them out and see if I can contribute with an example or two. 

Cheers,

Kf

**Comment by gaocegege** [comment]
Hi, Kf

The examples in reference are migrated from Processing reference, so if you'd like to contribute you could see [wiki](https://github.com/gaocegege/Processing.R/wiki/How-to-document-Processing.R) about how to document Processing.R.

Thank you for trying :smiley:

**Comment by gaocegege** [comment]
The mode has been released in PDE, so I think it is time to close it.

**Comment by jeremydouglass** [comment]
@gaocegege I was going to remind you to also update the readme... but you already did it!

@kfrajer, definitely let us know by pull request or in the forum if you want to contribute any example sketches.
