### ISSUE TITLE
When there are exceptions, fail to close the applets

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#143]
Python mode has the same bug

ref https://vimeo.com/224415544

![image](https://user-images.githubusercontent.com/5100735/27894937-e2cda64e-6241-11e7-988a-3fd23cc3d626.png)

@jdf

**Comment by jdf** [comment]
Does not reproduce for me. When I run that sketch, the single letter ```r```, I get that same error, but no sketch window appears (as expected).

**Comment by jeremydouglass** [comment]
This doesn't reproduce for me with the test `r` sketch using the latest master of Processing.R and running on PDE 3.3.5 / macOS 10.12.5.

Instead I get the following console error:

> object 'r' not found  
> 	  at rprocessing.exception.RSketchError.toSketchException(Unknown Source)  
> 	  at rprocessing.RLangPApplet.setup(Unknown Source)  
> 	  at processing.core.PApplet.handleDraw(PApplet.java:2412)  
> 	  at rprocessing.RLangPApplet.handleDraw(Unknown Source)  
> 	  at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)  
> 	  at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

**Comment by gaocegege** [comment]
The first time I run the code, everything works well, but it fails at the second time.

**Comment by jeremydouglass** [comment]
Strange. No matter how many times I press "run" it always generates the same error message -- no floating window left behind, even if I click "run" as fast as I can.

Might be a Linux-specific issue (I'm testing on Mac) -- or a race condition?

Some *possibly* related types of issues in Processing:

-  quickly clicking Stop after Run will prevent sketch from being stopped https://github.com/processing/processing/issues/4283
-  Movie Maker only works once per session (subsequent uses require restart of PDE) https://github.com/processing/processing/issues/5168
-  Can't re-open sketch after closing the PDE https://github.com/processing/processing/issues/5073

**Comment by gaocegege** [comment]
Yeah, I think it is maybe a linux-specific issue.

**Comment by jeremydouglass** [comment]
@gaocegege -- does this issue still exist on Linux in the current release?

If not let's close (can't-reproduce), and re-open if we get a confirming report. If it does, add to Someday.

**Comment by gaocegege** [comment]
No, I could not reproduce it. I will close it.
