### ISSUE TITLE
howto.md: Document the new way

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#159]
Now we could download the mode from release page, so there is no need to build the mode from source code.

My suggestion is to split two files, one is for users, other is for developers. We could recommend users to download the mode from release page. And move the instructions about building from source code to developer's manual.

**Comment by gaocegege** [comment]
BTW, there is an error in howto, IMO.

The location of mode folder in Windows is not `%homepath%\Documents\modes\`. It should be `%homepath%\Documents\Processing\modes\`, so [here](https://github.com/gaocegege/Processing.R/blob/43370ed0e3d91d32537f638851bc36f67786318e/raw-docs/howto.md#configure-script) should be updated.

**Comment by jeremydouglass** [comment]
Good idea to make developer instructions separate.

Also keep in mind that eventually many users won't even download the release directly -- they will just look it up in the PDE Contributions Manager under modes and install it there.
