### ISSUE TITLE
Support more built-in functions 

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#16]
Now Processing.R supports draw, setting and some other functions but not enough. 

ref https://processing.org/reference/

## 2D Primitives

- [x] <a href="https://processing.org/reference/arc_.html" class=" ref-link">arc()</a>
- [x] <a href="https://processing.org/reference/ellipse_.html" class=" ref-link">ellipse()</a>
- [x] <a href="https://processing.org/reference/line_.html" class=" ref-link">line()</a>
- [x] <a href="https://processing.org/reference/point_.html" class=" ref-link">point()</a>
- [x] <a href="https://processing.org/reference/quad_.html" class=" ref-link">quad()</a>
- [x] <a href="https://processing.org/reference/rect_.html" class=" ref-link">rect()</a>
- [x] <a href="https://processing.org/reference/triangle_.html" class=" ref-link">triangle()</a>

## Curves

- [x] <a href="https://processing.org/reference/bezier_.html" class=" ref-link">bezier()</a>
- [x] <a href="https://processing.org/reference/bezierDetail_.html" class=" ref-link">bezierDetail()</a>
- [x] <a href="https://processing.org/reference/bezierPoint_.html" class=" ref-link">bezierPoint()</a>
- [x] <a href="https://processing.org/reference/bezierTangent_.html" class=" ref-link">bezierTangent()</a>
- [x] <a href="https://processing.org/reference/curve_.html" class=" ref-link">curve()</a>
- [x] <a href="https://processing.org/reference/curveDetail_.html" class=" ref-link">curveDetail()</a>
- [x] <a href="https://processing.org/reference/curvePoint_.html" class=" ref-link">curvePoint()</a>
- [x] <a href="https://processing.org/reference/curveTangent_.html" class=" ref-link">curveTangent()</a>
- [x] <a href="https://processing.org/reference/curveTightness_.html" class=" ref-link">curveTightness()</a>

## Environments

- [ ] <a href="https://processing.org/reference/delay_.html" class=" ref-link">delay()</a>
- [ ] <a href="https://processing.org/reference/displayDensity_.html" class=" ref-link">displayDensity()</a>
- [ ] <a href="https://processing.org/reference/focused.html" class=" ref-link">focused</a>
- [ ] <a href="https://processing.org/reference/frameCount.html" class=" ref-link">frameCount</a>
- [ ] <a href="https://processing.org/reference/frameRate_.html" class=" ref-link">frameRate()</a>
- [ ] <a href="https://processing.org/reference/frameRate.html" class=" ref-link">frameRate</a>
- [ ] <a href="https://processing.org/reference/fullScreen_.html" class=" ref-link">fullScreen()</a>
- [ ] <a href="https://processing.org/reference/height.html" class=" ref-link">height</a>
- [ ] <a href="https://processing.org/reference/noSmooth_.html" class=" ref-link">noSmooth()</a>
- [ ] <a href="https://processing.org/reference/pixelDensity_.html" class=" ref-link">pixelDensity()</a>
- [ ] <a href="https://processing.org/reference/pixelHeight.html" class=" ref-link">pixelHeight</a>
- [ ] <a href="https://processing.org/reference/pixelWidth.html" class=" ref-link">pixelWidth</a>
- [x] <a href="https://processing.org/reference/settings_.html" class=" ref-link">settings()</a>
- [x] <a href="https://processing.org/reference/size_.html" class=" ref-link">size()</a>
- [ ] <a href="https://processing.org/reference/smooth_.html" class=" ref-link">smooth()</a>
- [x] <a href="https://processing.org/reference/width.html" class=" ref-link">width</a>

## 3D Primitives

- [x] <a href="https://processing.org/reference/box_.html" class=" ref-link">box()</a>
- [ ] <a href="https://processing.org/reference/sphere_.html" class=" ref-link">sphere()</a>
- [ ] <a href="https://processing.org/reference/sphereDetail_.html" class=" ref-link">sphereDetail()</a>

### Setting

- [x] <a href="https://processing.org/reference/background_.html" class=" ref-link">background()</a>
- [x] <a href="https://processing.org/reference/clear_.html" class=" ref-link">clear()</a>
- [x] <a href="https://processing.org/reference/colorMode_.html" class=" ref-link">colorMode()</a>
- [x] <a href="https://processing.org/reference/fill_.html" class=" ref-link">fill()</a>
- [x] <a href="https://processing.org/reference/noFill_.html" class=" ref-link">noFill()</a>
- [x] <a href="https://processing.org/reference/noStroke_.html" class=" ref-link">noStroke()</a>
- [x] <a href="https://processing.org/reference/stroke_.html" class=" ref-link">stroke()</a>

### Creating & Reading

Blocked until #9 

- [ ] <a href="https://processing.org/reference/alpha_.html" class=" ref-link">alpha()</a>
- [ ] <a href="https://processing.org/reference/blue_.html" class=" ref-link">blue()</a>
- [ ] <a href="https://processing.org/reference/brightness_.html" class=" ref-link">brightness()</a>
- [ ] <a href="https://processing.org/reference/color_.html" class=" ref-link">color()</a>
- [ ] <a href="https://processing.org/reference/green_.html" class=" ref-link">green()</a>
- [ ] <a href="https://processing.org/reference/hue_.html" class=" ref-link">hue()</a>
- [ ] <a href="https://processing.org/reference/lerpColor_.html" class=" ref-link">lerpColor()</a>
- [ ] <a href="https://processing.org/reference/red_.html" class=" ref-link">red()</a>
- [ ] <a href="https://processing.org/reference/saturation_.html" class=" ref-link">saturation()</a>

**Comment by PatrickMurphy** [comment]
Gaocegege, I am interested in contributing to this repo, If you have any direction of what issues, or what built in functions you would like to prioritize I would be happy to claim some of the work and send pull requests.

**Comment by gaocegege** [comment]
@PatrickMurphy Thanks for your interest 🎉 

Today, I'll write some documentation about the architecture of Processing.R and tag some issues to "for new contributors". If you have any problems when you read the code, feel free to @ me in GitHub or https://gitter.im/gaocegege/Processing.R.

**Comment by gaocegege** [comment]
re @PatrickMurphy 

ref https://github.com/gaocegege/Processing.R/issues/16#issue-212944608 Processing.R will focus on 2D & 3D Primitives at the first.

Functions such as arc() and ellipse() are easy to implement. If you want to contribute, this is a good entrypoint :)

**Comment by jeremydouglass** [comment]
@gaocegege -- this built-in functions list includes `cursor()`.

Is it part of the plan support mouse input and interaction like `mouseX` `mouseY` `mousePressed()` `mouseReleased()` -- or will the first phase stay focused on non-interactive sketches? Without mouse interaction there isn't much point in a `cursor()` command.

**Comment by jeremydouglass** [comment]
Also, should `box()` be crossed off the list? It looked like it was implemented for the 3d-cube.R example.

**Comment by gaocegege** [comment]
@jeremydouglass 

box in Processing has two definitions: `box(size)` and `box(w, h, d)`, I only implement one for the 3D example. I treat the example as a feasibility research, so I will add all 3d functions soon.

**Comment by gaocegege** [comment]
Hi, there are too many built-in functions in Processing, so I am not sure if I have the ability to implement all functions on my own in the first evaluation. I am trying to attract some contributors to Processing.R and we could also talk about the priority between the functions and have a more detailed plan.

**Comment by jeremydouglass** [comment]
@gaocegege --

You definitely *should not* try to implement all the built-ins on your own!

I would suggest either removing `cursor()` from the list entirely or else putting it in its own section alongside with the other mouse related functions. Mouse interaction would probably be an advanced issue for a contributor, so maybe far down the list.

Strange, I thought you had implemented both versions of box:

https://github.com/gaocegege/Processing.R/blob/abec5d7a832ad05260eb7256c6a2ab514e3283b7/src/rprocessing/applet/BuiltinApplet.java#L213

**Comment by gaocegege** [comment]
Oh, I forgot that. 🤔 Thanks for your review.

**Comment by gaocegege** [comment]
Yeah, I will remove cursor from the list.

**Comment by gaocegege** [comment]
Now renjin supports float correctly, so no need to do this work manually.

**Comment by jeremydouglass** [comment]
Fastastic! Great ask, hooray for the Renjin core developers, and hooray for open source.

...and that should simplify hundreds of `super` calls.

**Comment by jeremydouglass** [comment]
Fastastic! Great ask, hooray for the Renjin core developers, and hooray for open source.

...and that should simplify hundreds of `super` calls.

**Comment by jeremydouglass** [comment]
Fastastic! Great ask, hooray for the Renjin core developers, and hooray for open source.

...and that should simplify hundreds of `super` calls.

**Comment by jeremydouglass** [comment]
Fastastic! Great ask, hooray for the Renjin core developers, and hooray for open source.

...and that should simplify hundreds of `super` calls.

**Comment by jeremydouglass** [comment]
Fastastic! Great ask, hooray for the Renjin core developers, and hooray for open source.

...and that should simplify hundreds of `super` calls.

**Comment by gaocegege** [comment]
See bedatadriven/renjin#319

Now I think we could close the issue 🎉

**Comment by jeremydouglass** [comment]
So at this point every method from the API is automatically inherited? And the only remaining issue is with variables -- width, height, frameCount, frameRate, looping, focused, etc?

**Comment by gaocegege** [comment]
Yes, I think so 🤔

**Comment by jeremydouglass** [comment]
Since this is closed, is there a separate, open issue for variables -- `width`, `height`, `frameCount`, `frameRate`, `looping`, `focused` etc.? They are currently listed on this closed issue, but not resolved.

Perhaps edit the issue and remove them from the list, and add them to a separate issue.

**Comment by jeremydouglass** [comment]
Similarly, "Creating & Reading" is listed in the issue as "Blocked until #9" -- if this is still true then create another separate issue for these and delete them from this closed issue built-ins list.

**Comment by gaocegege** [comment]
ref #81 

Yeah, I will file a new issue.

**Comment by jeremydouglass** [comment]
Let's clean up this old list. Can all the "blocked until 9" be checked off now that https://github.com/gaocegege/Processing.R/issues/86 is closed?

**Comment by gaocegege** [comment]
All the functions in the list are supported.
