### ISSUE TITLE
Support the event function

### ISSUE THREAD

**Issue by hawkingrei** [gaocegege/Processing.R#163]
The event function is call when the event has happen. 

the code is inspired by processing.py
```python
value = 0

def draw(): 
    fill(value)
    rect(25, 25, 50, 50)

def mouseClicked(): 
    global value
    if value == 0:
        value = 255
    else:
        value = 0
```

**Comment by gaocegege** [comment]
Only `mouseClicked `? Is there any other functions or could you give me a link?

It is a good idea 👍

**Comment by hawkingrei** [comment]
[mouseClicked()](http://py.processing.org/reference/mouseClicked.html)
[mouseDragged()](http://py.processing.org/reference/mouseDragged.html)
[mouseMoved()](http://py.processing.org/reference/mouseMoved.html)
[mousePressed()](http://py.processing.org/reference/mousePressed.html)
[mouseReleased()](http://py.processing.org/reference/mouseReleased.html)
[mouseWheel()](http://py.processing.org/reference/mouseWheel.html)
[keyPressed()](http://py.processing.org/reference/keyPressed.html)
[keyReleased()](http://py.processing.org/reference/keyReleased.html)
[keyTyped()](http://py.processing.org/reference/keyTyped.html)

**Comment by jeremydouglass** [comment]
In Processing the interactivity model has two parts:

1. built-in variables like mouseX, mouseY, keyPressed, key, and keyCode, which are automatically updated each frame and can be used inside draw().
2. event functions like mouseClicked(), keyPressed() etc. (listed above) which contain arbitrary code. Keyboard and mouse events are automatically processed at the end of each draw() frame with calls to the event functions.

https://processing.org/tutorials/interactivity/

**Comment by gaocegege** [comment]
I am on it :tada:
