### ISSUE TITLE
Add tutorials

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#186]
* Documentation is important, although it is so big that it could be done forever -- so maybe a few crucial improvements, then leave the rest for contributors.

**Comment by gaocegege** [comment]
@jeremydouglass Do you have any suggestions for this issue? IMO we need a guide page just like https://processing.org/. But we already have readme.md. I am not sure what we should do.

**Comment by jeremydouglass** [comment]
What guide page are you referring to?

Do you mean http://py.processing.org/tutorials/ ?

**Comment by jeremydouglass** [comment]
Also, adding a guide is important , there are several issues with the documentation that could be improved with daily work:

1. Remove Python-specific reference terms from reference import #120 -- sometimes bad documentation is worse than no documentation!
2. Fix ad-hoc examples in documentation #110 -- most of these now use newly supported features, and can be easily fixed / resolved.
3. docs: Reference Documentation #131

We assume that many parts of Processing.R now work, but we don't have (e2e) test coverage for most of the API because we haven't done docs for those functions. Doing at least some of these (a few from each category) would give us a much better idea of how Processing.R works and if it will need to be improved in the future.

**Comment by gaocegege** [comment]
Yeah, something like http://py.processing.org/tutorials/, but I don't know how to do it.

And I agree with you about the daily work. I will focus on these issues and try to find a way to add the guide into P.R

**Comment by jeremydouglass** [comment]
Great to hear! I will review the Processing.py tutorials -- which are based on the Processing tutorials -- and get back to you on that.

**Comment by jeremydouglass** [comment]
OK.

The Processing.py Mode tutorials are a copy of the Processing.org tutorials, only with the snippets of Java code replaced with Python code.

-  http://py.processing.org/tutorials/
-  https://processing.org/tutorials/

So, the easiest way to incorporate this material into the Processing.R documentation website would be:

1. Copy a tutorial from Processing Tutorials -- e.g. Color: https://processing.org/tutorials/color/
2. Modify the statement on top.  Processing.org says:

      > This tutorial is from the book Learning Processing by Daniel Shiffman, published by Morgan Kaufmann, © 2008 Elsevier Inc. All rights reserved. If you see any errors or have comments, please let us know.

    and py.processing.org says:

      > This tutorial is for Processing's Python Mode. If you see any errors or have comments, please let us know. This tutorial is adapted from the book, Learning Processing, by Daniel Shiffman, published by Morgan Kaufmann Publishers, Copyright © 2008 Elsevier Inc. All rights reserved.

    so Processing.R should say something like:

      > This tutorial is for Processing's R Mode. It is adapted from the book Learning Processing by Daniel Shiffman, published by Morgan Kaufmann Publishers, Copyright © 2008 Elsevier Inc. All rights reserved. If you see any errors or have comments, please let us know. 

3. Modify the example code snippets from Java to R -- as well as code described directly in the paragraphs or images, if any exists. Many of the simple examples are already valid R -- they only need the comments changed from `//` to `#`:

    ```
    background(255);    # Setting the background to white
    stroke(0);          # Setting the outline (stroke) to black
    fill(150);          # Setting the interior of a shape (fill) to grey 
    rect(50,50,75,100); # Drawing the rectangle
    ```

Start out by doing 1-2 simple tutorials to get started. Notice that Processing.py didn't copy *all* the tutorials -- just the most important ones.

Any questions about this?

**Comment by gaocegege** [comment]
https://processing-r.github.io/

I added the credits, and need your suggestions :smile:

**Comment by jeremydouglass** [comment]
See my comment on other issue.

In this issue, are you still thinking about adding a test tutorial page?

**Comment by gaocegege** [comment]
Yeah, I am thinking about it, at least a tutorial like https://processing.org/tutorials/gettingstarted/

**Comment by jeremydouglass** [comment]
Great -- looking forward to it!

[Getting started](https://processing.org/tutorials/gettingstarted/) is a great place to start. Also
in my experience one of the most useful ones for newcomers is the [2D Transformations](https://processing.org/tutorials/transform2d/) tutorial.

**Comment by gaocegege** [comment]
Yeah, it is also in high priority

**Comment by gaocegege** [comment]
https://processing-r.github.io/tutorials/

We have a page for tutorials now :tada:
