### ISSUE TITLE
Credits in Processing.R reference docs

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#206]
ref https://github.com/gaocegege/Processing.R/commit/50d260c3d61fabb5fcca201b79da493046b5d083#commitcomment-23555490

**Comment by gaocegege** [comment]
ref https://processing-r.github.io/

Does it works for you? @jeremydouglass

**Comment by jeremydouglass** [comment]
I like the language -- "chiefly developed _, with contributions by _" is an important addition.

Still to-do:

https://github.com/gaocegege/Processing.R/commit/50d260c3d61fabb5fcca201b79da493046b5d083#commitcomment-23554818

> The Processing.R docs site should have credits (at least a general credit) that lists the Processing docs, Processing.py docs, and R docs.

For example, you could add this below the existing "inspired by" credits on the docs homepage:

> The Processing.R Reference for Processing functions is based on materials from the [Processing Reference](https://processing.org/reference/) and [Processing.py Reference](http://py.processing.org/reference/). Documentation for structural features of the R language is based on the [R Documentation for package ‘base’](http://stat.ethz.ch/R-manual/R-patched/library/base/html/00Index.html) (v3.4.1).

**Comment by gaocegege** [comment]
OK, I will deal with it.

**Comment by gaocegege** [comment]
Ref https://processing-r.github.io/

**Comment by jeremydouglass** [comment]
Looks great!
