### ISSUE TITLE
Announce mode

### ISSUE THREAD

**Issue by jeremydouglass** [gaocegege/Processing.R#215]
1. Post an announcement that the Processing.R mode is now available through the PDE Contributions Manager. It should appear in the channel Create & Announce Modes: https://forum.processing.org/two/categories/create-announce-modes
2. Post a comment with a link to the new announcement at the end of the existing Idea forum thread. https://forum.processing.org/two/discussion/21195/idea-r-language-mode-for-processing
3. Post the announcement text to https://groups.google.com/forum/#!forum/renjin-dev ... add a first line: "Announcing a new Processing.R mode built using renjin:"
4. ...anywhere else we should be announcing?

**Comment by gaocegege** [comment]
1. https://forum.processing.org/two/discussion/23848/ann-r-language-mode-for-processing-available-in-pde
2. https://forum.processing.org/two/discussion/comment/104160/#Comment_104160
3. https://groups.google.com/forum/#!topic/renjin-dev/eSoqmb06lCc

**Comment by jeremydouglass** [comment]
A wonderful launch!

**Comment by gaocegege** [comment]
There are some other ways:

* https://www.reddit.com/r/processing/
* https://twitter.com/ProcessingOrg
* https://news.ycombinator.com/news

**Comment by jeremydouglass** [comment]
Good ideas -- these all sound good to me. On the forum GoToLoop is very active in the reddit group.

**Comment by gaocegege** [comment]
😄 And I have sent you an email to discuss the meeting, Does my Tuesday 11:00 pm / your Monday 8:00 am(Tomorrow) works for you?

**Comment by jeremydouglass** [comment]
Can't -- baby has a doctor's apt. at 8am. I could chat now though...?

**Comment by gaocegege** [comment]
* https://www.reddit.com/r/processing/comments/6vgkkp/r_language_for_processing_new_mode_available_in/

**Comment by gaocegege** [comment]
https://twitter.com/gaocegege/status/900216517266198530
