### ISSUE TITLE
Get in touch with R community

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#34]
> Once there is something to ask them that is a good idea for getting feedback . We may want to request feedback on aspects of the work plan -- and later recruit testers if we can.

**Comment by gaocegege** [comment]
## Forum List

* https://www.reddit.com/r/Rlanguage/

### Chinese

* http://cos.name/cn/

**Comment by gaocegege** [comment]
There is a post in cos: http://cos.name/cn/topic/418615/

**Comment by gaocegege** [comment]
ref https://github.com/cosname/cosx.org/issues/542#event-1075830674

When GSoC finishes, I will file a post to cos and introduce the project into R users in China.

**Comment by jeremydouglass** [comment]
@gaocegege -- does PDE have good Chinese localization -- are you using it? I saw this:

https://github.com/processing/processing/blob/master/build/shared/lib/languages/PDE_zh.properties

I'm not sure if Processing modes have any built-in localization support, but that also might be worth looking into for Chinese R users after GSOC finishes.

**Comment by gaocegege** [comment]
Yeah, PDE's Chinese localization is great. Localization support is in low priority, I think 🤔

**Comment by gaocegege** [comment]
I will write a post and send it to https://cosx.org/, the most famous R community in China.

**Comment by jeremydouglass** [comment]
Good luck on writing it!

I would recommend only using pictures 2,3,4 -- pictures 1 & 2 are redundant, so no need to use 1.

**Comment by jeremydouglass** [comment]
Also keep in mind that we have a future issue for localization support

https://github.com/gaocegege/Processing.R/issues/78

Processing itself already has Chinese localization here:

https://github.com/processing/processing/blob/master/build/shared/lib/languages/PDE_zh.properties

...and docs for translating here:

https://github.com/processing/processing/wiki/Localization

...but I'm not sure if modes / libraries can be localized -- or if they should be. If so we could ask for volunteers from participating language communities.

**Comment by gaocegege** [comment]
Preview: https://deploy-preview-709--cosx.netlify.com/2017/08/processing-r/
