### ISSUE TITLE
Comments highlight error in Processing IDE

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#35]
![2017-05-08 13-50-57](https://cloud.githubusercontent.com/assets/5100735/25791904/f90383ea-33f5-11e7-918e-b9fb71d5ee5c.png)

**Comment by jeremydouglass** [comment]
Could you update this closed bug with a very brief description of what error you were seeing in the screenshot?

**Comment by gaocegege** [comment]
Yeah, I comment the lines from `for` to `}` but the code still be in keyword color.

The color should be grey, just like:

<img width="534" alt="2017-05-16 9 38 54" src="https://cloud.githubusercontent.com/assets/5100735/26108860/4ae7d02c-3a80-11e7-9114-04eaf544c2fb.png">
