### ISSUE TITLE
Add an object oriented example

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#41]

**Comment by gaocegege** [comment]
matrix is a bad idea to store a object since oject is a list, actually in S3

**Comment by gaocegege** [comment]
Try list now

**Comment by gaocegege** [comment]
@jeremydouglass
:tada: It works.

IMO, R, Java and Processing are all [Turing complete](https://en.wikipedia.org/wiki/Turing_completeness), I think R's OO could do well as Processing does but the code may be a little complex :thinking:

**Comment by jeremydouglass** [comment]
@gaocegege --

Great example!! Also, native S3 support that works means that we can assume we are on the right path for future support of advanced sketches -- even if focusing on that isn't a big part of this GSOC.

re:

> I think R's OO could do well as Processing does but the code may be a little complex

Processing is often targeting language learners, so if there is a choice between 1) creating examples or tutorials in the future using a complex OO code and 2) a simpler non-OO approach, simple might often win. Processing.py and p5.js translated a lot of "standard" example sketches from Processing(Java), so in the future trying to adapt some of those existing sketches into Processing.R using a readable style might be a good way to figure out when or how to use R-style OO -- and when not to.
