### ISSUE TITLE
PDE mode installation (manual)

### ISSUE THREAD

**Issue by jeremydouglass** [gaocegege/Processing.R#42]
Currently Processing.R has three methods of distribution as per https://github.com/gaocegege/Processing.R/blob/master/raw-docs/howto.md

-  download a docker container and interact via NoVNC web browser
-  download modified PDE as the package at http://gaocegege.com/Processing.R/
-  build modified PDE from source

In Processing the normal way to use a new mode is:

1. install the standard Processing IDE (PDE)
2. add the mode using Tools > Add Tool > Modes.

If a mode is not available from Processing, manual mode installation generally works like this:

1. install the standard PDE
2. check out the mode source for its repository
3. type `make` at the repository root directory.
4. copy `dist/MyMode/` directory into the Processing modes directory:
    -  MacOSX: ~/Documents/Processing/modes/
    -  Windows: %homepath%\Documents\modes\
    -  Linux: ~/sketchbook/modes/
5. Reboot PDE

For an example of this, see Ruby mode: https://github.com/tyfkda/processing-ruby-mode

Is there a reason that the manual method of PDE mode distribution would not work for Processing.R?

**Comment by jeremydouglass** [comment]
I have not yet tried building the latest Processing.R from source.

I have downloaded the old v1.0.1 app image (which worked, but encounters errors on testing the latest example sketches e.g. OO).

I have run the docker image (which runs, but I was unable to connect to either VNC port using the url and password instructions, and the container failed to exit gracefully). Ce, I know you mentioned that you would probably remove the docker build in the future, as it is "not a good fit" for Processing.

**Comment by gaocegege** [comment]
Yeah, I have tried to install R mode with the existing PDE, but failed to force PDE to discover R mode.

It seems to be some errors during the class loading in JVM, I will pay more attention to this issue.

**Comment by gaocegege** [comment]
> I have downloaded the old v1.0.1 app image (which worked, but encounters errors on testing the latest example sketches e.g. OO).

Do you mean the dmg image or docker image 🤔 . And there are so many changes between v1.0.1 and master: [CHANGELOG](https://github.com/gaocegege/Processing.R/blob/master/CHANGELOG.md#unreleased). It is acceptable to meet errors when using the OOP example.

> I have run the docker image (which runs, but I was unable to connect to either VNC port using the url and password instructions, and the container failed to exit gracefully). Ce, I know you mentioned that you would probably remove the docker build in the future, as it is "not a good fit" for Processing.

I will take a look on it. I thinks docker is not the best way because [the demo](https://vimeo.com/207571123) shows that the resolution is definitely low in the docker container and I think it will hurt people. If I am a newcomer to Processing.R and run the container, I will leave the repository 🤔 

What do you think? If we continue the Docker way, then we could do:

* Find a way to increase the resolution
* Support PDE in container, not only Processing.R runner.

**Comment by jeremydouglass** [comment]
Right -- it is expected that 1.0.1 app image would not work.

Personally I think that you should not spend any time on container-based distribution -- leave it alone, instead see if the issue can be resolved with using a manually added / standard mode and PDE discovering that mode. If it can then drop the container.

**Comment by gaocegege** [comment]
It makes sense. I will work on the first problem.

**Comment by gaocegege** [comment]
I think now it works for the existing PDE. I will add the documentation soon. It is similar to what https://github.com/tyfkda/processing-ruby-mode does.

run `ant package` to get the mode from `dist/`, then move the dist to the corresponding location according to OS. Then processing could use R mode.

**Comment by gaocegege** [comment]
There is something wrong in macOS :( I will take a look.

**Comment by gaocegege** [comment]
Ref #47 

The work has been done in #44

**Comment by gaocegege** [comment]
Now the changes have been merged into master, have a try on master :)

**Comment by jeremydouglass** [comment]
I was able to install the mode into my existing PDE:

```
./scripts/generate-ant-file.sh
ant install
``` 

The generate-ant-file.sh script is set up for building both Processing core and PDE from source, but this doesn't make sense for the scenario where you are adding a new mode to the existing canonical PDE. For just building the mode against the existing (official) PDE app, generate-ant-file.sh 
 can be something more like this:

```
modes="/Users/usename/Documents/Processing/modes"
executable="/Applications/Processing.app/Contents/MacOS/Processing"
core="/Applications/Processing.app/Contents/Java/"
pde="/Applications/Processing.app/Contents/Java/"
````

**Comment by gaocegege** [comment]
OK, I will take a look.

**Comment by gaocegege** [comment]
Do you think it is ok to set the core and pde to the corresponding jar?

**Comment by jeremydouglass** [comment]
Yes -- I think that is fine.

**Comment by gaocegege** [comment]
The issue has been solved via #60 :tada:

**Comment by gaocegege** [comment]
I have not tested it in macOS. And there are some documentation remains to be updated.

**Comment by gaocegege** [comment]
It works well in macOS, so close it 🎉
