### ISSUE TITLE
Install R examples while installing Processing.R mode

### ISSUE THREAD

**Issue by jeremydouglass** [gaocegege/Processing.R#48]
Currently, other modes (like p5.js, Processing.py, etc.) package their examples with the mode in an `examples` subdirectory:

    /Users/username/Documents/Processing/modes/p5jsMode/examples
    /Users/username/Documents/Processing/modes/PythonMode/examples
    etc.

This method of distributing mode examples fits with the general library guidelines:

> Examples. Users tend to learn best from examples, therefore examples are important for a library release. It is highly recommended to support your library with various sample programs to demonstrate the use and potential of the library.
> https://github.com/processing/processing/wiki/Library-Guidelines

At present, building and installing the Processing.R mode doesn't install the examples -- and creating an examples folder with the files is not enough for them to appear in the PDE "Processing.R Examples" menu of PDE after opening a new Processing.R Sketch. I haven't yet looked into whether this is:

1. a file-type filter problem (.R vs .pde vs. .pyde etc.)
2. a configuration that should be compiled into RLangMode.jar
3. something else

I'm currently able to test all of the example sketches manually -- very nice 3d-cube.R demo, by the way --  but if installing examples with the mode is fixed then it will be extremely easy for testers and community members to grab the latest Processing.R mode/examples from github and try them out in PDE. That should create more and higher quality feedback, help, and documentation.

If this is at all difficult -- e.g. it would require changes to Processing core beyond the scope of the mode -- another potential mechanism for distributing the Processing.R examples is to install them into a separate Example package using a properties file:

-  https://github.com/processing/processing/wiki/Examples-Overview

**Comment by gaocegege** [comment]
That is awesome. I am not aware of the difficulty about building and installing, since I have the development environment in my laptop. I think the issue should be in high priority. 👍

**Comment by gaocegege** [comment]
FYI, the issue has been closed by #57
