### ISSUE TITLE
Support render keywords in size()

### ISSUE THREAD

**Issue by jeremydouglass** [gaocegege/Processing.R#50]
The Processing `size()` command takes keywords for each renderer. In addition to the default renderer, other renderers are: (from https://processing.org/reference/size_.html )

- [x] P2D (Processing 2D): 2D graphics renderer that makes use of OpenGL-compatible graphics hardware.
- [x] P3D (Processing 3D): 3D graphics renderer that makes use of OpenGL-compatible graphics hardware.
- [x] FX2D (JavaFX 2D): A 2D renderer that uses JavaFX, which may be faster for some applications, but has some compatibility quirks. 
- [x] PDF: The PDF renderer draws 2D graphics directly to an Acrobat PDF file. 

So, currently the Processing.R example sketch 3d-cube.R:

```
settings <- function()
{
  processing$size(500, 500, "processing.opengl.PGraphics3D")
}
```

Would become:

```
settings <- function()
{
  processing$size(500, 500, P3D)
}
```

While this issue is unresolved, I would recommend that current and future example sketches have render keywords defined in the header so that `settings()` more closely mirrors normal Processing code -- using this style:

```
P3D <- "processing.opengl.PGraphics3D"
settings <- function()
{
  processing$size(500, 500, P3D)
}
```

----

Supporting render keywords in Processing.R will make it much easier to translate sketches back and for between Processing(Java) and Processing.R -- especially for new learners.

**Comment by jeremydouglass** [comment]
...related: I see that currently select keywords -- "width" "height" etc. -- are being mapped in RLangPApplet `wrapProcessingVariables()`:

https://github.com/gaocegege/Processing.R/blob/a5a51a9fcdf9032f56edff97003b0f65602bd31d/src/rprocessing/RLangPApplet.java#L206

**Comment by gaocegege** [comment]
Yeah it is a future work. I am not familiar with the logic of renjin about variable binding now.

ref https://forum.processing.org/two/discussion/comment/97742/#Comment_97742
