### ISSUE TITLE
support static sketches with size()

### ISSUE THREAD

**Issue by jeremydouglass** [gaocegege/Processing.R#51]
`size()` does not appear to work with Processing.R static sketches. 

Currently the "hello-processing.R" is an example is what Processing calls a *static sketch*:

> A program written as a list of statements (like the previous examples) is called a static sketch. In a static sketch, a series of functions are used to perform tasks or create a single image without any animation or interaction. Interactive programs are drawn as a series of frames, which you can create by adding functions titled setup() and draw() as shown in the code below. -
  https://processing.org/tutorials/overview/

Because `size()` does not work with static sketches, they cannot use 3D (using the P3D OpenGL renderer). For example, here is a static sketch in Processing(Java) showing how `box()` works:

```
size(100, 100, P3D);
translate(58, 48, 0); 
rotateY(0.5);
noFill();
box(40, 20, 50);
```

Here is the equivalent sketch in the current Processing.R without static `size()`:

```
P3D <- "processing.opengl.PGraphics3D"
settings <- function() {
 processing$size(100, 100, P3D)
}
setup <- function() {
  processing$noLoop()
}
draw <- function() {
  processing$translate(58, 48, 0)
  processing$rotateY(0.5)
  processing$noFill()
  processing$box(40, 20, 50)
}
# based on https://processing.org/reference/box_.html
```

----

Supporting size() in Processing.R static sketches will make example code and documentation much more concise -- which will make it easier to read for learners.

**Comment by gaocegege** [comment]
Yeah, I think it is a bug and I will try to fix it.
