### ISSUE TITLE
adopt style guide for R code and examples

### ISSUE THREAD

**Issue by jeremydouglass** [gaocegege/Processing.R#52]
All R example code and documentation should largely conform to some consistent R code style guide -- ideally one that already exists, rather than the project developing its own.

Here is one example:

-  Google's R Style Guide https://google.github.io/styleguide/Rguide.xml

Future documentation efforts would:

- [x] choose an R style guide
- [x] reference the chosen style guide in the wiki / documentation
- [x] correct issues of style in example code to conform

----

Example style consistency will be especially useful because some Processing.R users are more likely to be confused by readability issues, and may also be learning R syntax for the first time by way of Processing.

**Comment by jeremydouglass** [comment]
...it might also be worth reviewing all documentation and example R code for consistency using static analysis, e.g.:

-  lintr: https://github.com/jimhester/lintr

**Comment by gaocegege** [comment]
I have imported coala as a command line code linting tool, which will check the style of the code(both Java and R). Thanks to the awesome tool, the code has been prettified.

And I add coala into ci. If there are some issues about code style in the code, the CI build will fail.

**Comment by jeremydouglass** [comment]
Great work!

**Comment by gaocegege** [comment]
😄 Thanks
