### ISSUE TITLE
Documentation: PDE reference folder in mode

### ISSUE THREAD

**Issue by jeremydouglass** [gaocegege/Processing.R#55]
Someday:

Processing.R may wish to integrate its reference (right-click to look up) into the Processing IDE directly through the mode distribution. This is how the PDE supports right-click-to-look-up in Processing(Java).

Processing modes automatically do URL lookups in a mode-specific references folder, e.g.:

    ~/Documents/Processing/modes/PythonMode/reference
    ~/Documents/Processing/modes/RLangMode/reference

However, this isn't supported in the current Processing.py -- and I'm not sure if p5.js is using it either. It might be worth asking why before using it:

-  https://github.com/jdf/processing.py/issues/235
-  https://github.com/jdf/processing.py/issues/228

If Processing.R supports only a subset of Processing and has some exceptions and special rules, then documentation will be important to making it useable. Ideally, this documentation could be added to the mode directly, automatically available via right-click lookup in the PDE, and also used to generate online documentation.

**Comment by jeremydouglass** [comment]
I've been opening these issues unlabeled so that you can think about priority, milestones, etc., but many of them are low priority -- some may not be addressed at all during GSOC.

My goal is not to overwhelm you with an enormous to-do list, but to introduce you to some of the strategic considerations for how modes in Processing are documented, illustrated with examples, integrated into the IDE, distributed via Add Tools, etc. etc. This is both low priority compared to basic mode functionality and very high priority, in the sense that some of these things (like #48) greatly assist community participation in testing and feedback and aid in adoption.

On the other hand, the right-click reference hasn't been a priority for all modes, so it may not offer the same strategic opportunity.

**Comment by gaocegege** [comment]
ref https://github.com/jdf/processing.py/issues/261

**Comment by jeremydouglass** [comment]
@jdf -- Sometime in the future we might want to integrate the PDE reference lookup into the Processing.R mode.

I noticed that Processing.py doesn't support this. Do you happen to know if a mode using the reference lookup is possible, or particularly hard? We haven't tested the feasibility yet.

**Comment by jdf** [comment]
Sorry; I haven't looked into how to do that.

**Comment by gaocegege** [comment]
@jeremydouglass Processing implement the logic in [Editor.java](https://sourcegraph.com/github.com/processing/processing/-/blob/app/src/processing/app/ui/Editor.java?q=find_in_reference#L2319-2331:4)

**Comment by jeremydouglass** [comment]
@gaocegege -- looks great. Online is fine -- I don't think that we need to bundle the entire reference with the mode the way that the core Processing(Java) mode does, although if there is demand someday for an offline reference we could easily add that as a feature.

@jdf if you ever want to add reference lookup to Processing.py it looks like gaocegage found the solution handleFindReference(), probably in PyEditor.java, as per 227

- https://github.com/jdf/processing.py/blob/master/runtime/src/jycessing/mode/PyEditor.java
- https://github.com/gaocegege/Processing.R/pull/227/files

**Comment by jdf** [comment]
Thank you!

**Comment by jdf** [comment]
Rather than duplicate the parent class's implementation, I chose to do it like so: https://github.com/jdf/processing.py/commit/6bca00ef2e02d27ae57254af406ea439eb25a744

**Comment by gaocegege** [comment]
Better implementation 😄
