### ISSUE TITLE
Support Processing libraries

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#58]
ref https://forum.processing.org/two/discussion/comment/97845/#Comment_97845

>And, before implementing new features in Processing, the mode should look (someday, in the future) at how renjin imports Java libraries -- no need to reinvent the wheel of plotting.
>
>The experience of the Processing.py mode with Java-libraries-in-Jython seems to have been this: Some Processing(Java) libraries worked without needing changes. Others required minor changes. Others needed a full separate version of the library or would not work at all.

**Comment by jeremydouglass** [comment]
For reference, this is how library Processing.py / Jython handles importing native Processing(Java) libraries.

https://github.com/jdf/processing.py/blob/master/runtime/src/jycessing/LibraryImporter.java

It looks quite complex -- I believe because a lot seems to be about auto-discovering non-jar resources.

The renjin documentation starting point for `import()` seems to be Ch5, p27: Importing Java Classes Into R Code:

https://media.readthedocs.org/pdf/renjin/latest/renjin.pdf#page31

I wonder if some very widely used Processing libraries are already importable and already work out-of-the-box, without changes to the renjin import mechanism.

**Comment by jeremydouglass** [comment]
Per our discussion: an example of a popular 3rd-party Processing library:

-  http://mrfeinberg.com/peasycam/
-  https://github.com/jdf/peasycam

Built-in libraries to consider starting with for testing:

-  https://processing.org/reference/libraries/video/index.html
-  https://processing.org/reference/libraries/pdf/index.html
-  https://processing.org/reference/libraries/serial/index.html

**Comment by gaocegege** [comment]
Now Processing.R supports libraries in PDE, for example, https://github.com/jdf/peasycam.

But it fails in Runner because of the libraries discovery in standalone sketch.

**Comment by jeremydouglass** [comment]
Initial library discovery work done in #133

**Comment by gaocegege** [comment]
The ad-hoc code has been fixed in #137

**Comment by gaocegege** [comment]
We need to test more libraries to test if the feature works well

**Comment by jeremydouglass** [comment]
Good idea!

1. Do we have an example library sketch?  
It could be the bases for a number of library sketches -- a simple example for each library. Easy to ask others to write them if there is a template. I could write a few myself.

2. Is there a test sketch for the library feature?  
Or would that not work with the testing setup?

**Comment by gaocegege** [comment]
1. I will write a example tomorrow.
2. Libraries are different with each other, I am afraid that it is hard to develop a framework to test all libraries just like e2etest does.

**Comment by jeremydouglass** [comment]
I agree that Processing.R does not need a library testing framework -- that too complex to be useful and out of scope!

Instead, I was wondering if, for example, the peasycam demo on Welcome Issue #142 could be added to test documentation for importLibrary(). Then as long as we had generated the target screenshot the test it would pass as long as peasycam was importing correctly, and fail if it wasn't. Not library specific testing, just an e2etest sanity check on importLibrary(). An issue would pre-installing peasycam into the CI environment to make it work.

settings <- function() {
    importLibrary("peasycam")
    size(200, 200, P3D)
}

setup <- function() {
    cam = PeasyCam$new(processing, 100)
    cam$setMinimumDistance(50)
    cam$setMaximumDistance(500)
}

draw <- function() {
    rotateX(-.5)
    rotateY(-.5)
    background(0)
    fill(255, 0, 0)
    box(30)
    pushMatrix()
    translate(0, 0, 20)
    fill(0, 0, 255)
    box(5)
    popMatrix()
}

**Comment by gaocegege** [comment]
Oh It is a good idea!

**Comment by jeremydouglass** [comment]
> because of the StandaloneSketch

Can you remind me why StandaloneSketch is a problem for importLibrary()?

**Comment by gaocegege** [comment]
StandaloneSketch doesn't implement the logic about the path to libraries. It could not find the libraries.

**Comment by gaocegege** [comment]
All tasks in Evaluation 2 are done :tada:

**Comment by jeremydouglass** [comment]
Wonderful. Let's schedule a meeting to check in and discuss before E2.
