### ISSUE TITLE
Docker: fail to run 3d sketches because of the device

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#63]
I tried to run Processing.R in PDE. It is generally feasible but fails to run 3d sketchs:

![2017-05-15 16-43-01](https://cloud.githubusercontent.com/assets/5100735/26049567/0a26e7b4-398e-11e7-8ebe-aee12353f74a.png)
![2017-05-15 16-43-44](https://cloud.githubusercontent.com/assets/5100735/26049573/11c06bbc-398e-11e7-889d-c498ffab5b9b.png)

It causes an error: https://forum.processing.org/two/discussion/1755/java-lang-runtimeexcetion-framebuffer-objects-are-not-supported-by-this-hardware-or-driver

Maybe we should give up docker now.

**Comment by gaocegege** [comment]
It may be solved by importing a graphic card into the container, but I have not idea where it works. And I don't know how to mount intel device into the container. The articles now are all about nvidia.

**Comment by jeremydouglass** [comment]
In my opinion docker work should be put on hold or cancelled. Unless there is a compelling reason that container distribution would offer some major advantage over PDEs built-in distribution?

**Comment by gaocegege** [comment]
Yeah, we should leave docker.

**Comment by gaocegege** [comment]
Close since we won't fix it.

**Comment by jeremydouglass** [comment]
I think it is a good idea to leave this closed won't-fix.

If someone wants to work on this in the future, the solution for P3D sketches not working in docker might be to change the base docker image to one that supports OpenGL:

-  https://github.com/thewtex/docker-opengl
-  https://github.com/thewtex/docker-opengl-nvidia

**Comment by gaocegege** [comment]
Yeah, and if you don't have a Nvidia graphic card, you could not use https://github.com/thewtex/docker-opengl-nvidia. I have not tried openGL support in docker without Nvidia, so it may be a better way to solve the problem
