### ISSUE TITLE
coala: Support code linting for Java

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#69]
ref https://github.com/coala/coala-bears/issues/1750

ref https://github.com/gaocegege/Processing.R/pull/67#issuecomment-302693462

> coala is a perfect tool to lint and format the code in command line. But it seems that there is something wrong. I will comment the checkstyle bear now and uncomment it until the bug is fixed.

**Comment by jeremydouglass** [comment]
coala/coala-bears#1750 is about 4-space indents.

[The Processing Style Guide](https://github.com/processing/processing/wiki/Style-Guidelines) uses 2-space indents:

> Always spaces, two of them. Never tabs.

...and the [Google Java Style Guide](http://google.github.io/styleguide/javaguide.html#s4.2-block-indentation) *also* uses two spaces:

> ** Block indentation: +2 spaces**  
> Each time a new block or block-like construct is opened, the indent increases by two spaces.

Maybe change the coala setting and relint all Java code to standard spacing? It sounds like that would also resolve this (via skipping 1750).

**Comment by jeremydouglass** [comment]
Nope, looks like it was probably the setting value after all. Please try 2 and rerun: the bear intentionally will not let you choose "4" because that violates Google's spec, as pointed out above. I'll respond on the coala issue thread.

**Comment by gaocegege** [comment]
I use eclipse as the IDE, and set [alibaba](https://www.alibaba.com/) style as the default formatter, which I think it is similar to google style, but it isn't. Then I will update the formatter setting to google in eclipse :)
