### ISSUE TITLE
New release (pre-GSOC)

### ISSUE THREAD

**Issue by jeremydouglass** [gaocegege/Processing.R#70]
There has been a lot of progress on Processing.R since v1.01! It would be nice to wrap up the latest progress in a new release, updating Github Releases and http://gaocegege.com/Processing.R/ .

This release would be a baseline before the official GSOC coding period begins at the end of the month.

Having a recent working release available will *also* mean that if we resolve #59 then we can invite early alpha testers to install the latest release of "Processing.R alpha" through the PDE Contributions Manager.

**Comment by jeremydouglass** [comment]
Also my suggestion would be that new releases should be the installable mode itself (the PDE mode folder) -- this folder can also include tools for command line and stand-alone runners.

The release should not including a docker container (which we are dropping anyway for now) and it should not including a full distribution of the Processing PDE -- only the mode itself. See for example how Processing Android Mode handles releases:

https://github.com/processing/processing-android/releases

This also will help integration with #59

**Comment by gaocegege** [comment]
Hi, Jeremy,

I am not sure if it is appropriate to release the new version to PDE, since it is incomplete. But a pre-GSoC release is needed. This time only the mode will be zipped and uploaded into the release page.

And as far as I can see, documentation is the most important thing to a new project, so I think the next thing we should do is to improve the documentation, then the mode is ready to early users 😺

**Comment by gaocegege** [comment]
## TODO

- Freeze commit https://github.com/gaocegege/Processing.R/commit/13148dc556c041a8d1d5f67c917731538a8b0d04 and package the mode
- Update release page http://gaocegege.com/Processing.R

**Comment by gaocegege** [comment]
Done, PTAL

- http://gaocegege.com/Processing.R
- https://github.com/gaocegege/Processing.R/releases/tag/v1.0.2
- https://github.com/gaocegege/Processing.R/wiki/Google-Summer-of-Code-2017

**Comment by jeremydouglass** [comment]
Excellent! All of the sources (GitHub source, release page, and homepage) work well, and distributing the mode folder (along with the example set) makes manually installation work easily with the PDE modes workflow.

These are clear, complete notes under the release, on the wiki page, and on your personal project homepage. Your consistent professional documentation of issues/commits/merges/pulls throughout the process really does a good job of communicating how much you accomplished just over the past month.

**Comment by jeremydouglass** [comment]
I agree about documentation! Let's review your GSOC plan, schedule a chat to lay out milestones and their relationship to review dates, and map existing and/or missing GitHub issues to milestones. A major documentation push should be an early milestone.

**Comment by gaocegege** [comment]
We could schedule the chat in #28 or by email :) The version is released then I think we should close the issue.
