### ISSUE TITLE
Refactor the logic about frameCount

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#81]
ref https://forum.processing.org/two/discussion/comment/97742/#Comment_97742

and ref https://github.com/gaocegege/Processing.R/commit/3894f094d43e5d315d7fec3bfe8d4e0a2da64e15#commitcomment-22322427

> Potentially relevant: almost all Processing sketches do not set frameCount, they only get it -- however, you can set frameCount, which is sometimes useful.
> 
> https://forum.processing.org/two/discussion/comment/87073/#Comment_87073

- [x] <a href="https://processing.org/reference/frameCount.html" class=" ref-link">frameCount</a>
- [x] <a href="https://processing.org/reference/frameRate.html" class=" ref-link">frameRate</a>

**Comment by gaocegege** [comment]
There should be a generic way to deal with this situation. Because I don't know if there are other variables which have the problem, too.

**Comment by gaocegege** [comment]
Maybe #121 could help us to solve this issue

**Comment by gaocegege** [comment]
FrameCount is refactored via https://github.com/gaocegege/Processing.R/commit/f32f09ad81b251139d52a2646357acea8ded77db

**Comment by jeremydouglass** [comment]
Does this mean that users can now update frameCount, or is frameCount still read-only?

```
frameCount <- 1
```

**Comment by gaocegege** [comment]
Oh, it is not supported in R mode, since the data binding is unidirectional

**Comment by jeremydouglass** [comment]
I've looked at other Processing(Java) variables that might relate to this issue, and they all have setter functions or don't need them -- `width` and `height` can be set by `size()`,  `focused` is fine as read-only,  `looping` can set by `loop()` / `noLoop()`,  and `frameRate` can be set by `frameRate()`.

So it seems that this isn't a general problem, which is good.

If we really wanted a workaround for `frameCount` perhaps we could add a non-API function that sets frameCount -- something like:

```
public void frameCount(int frame){
  this.frameCount = frame;
}
```
