### ISSUE TITLE
Support description and syntax in reference by .property.yml

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#93]
Now we have example code and image, but no description and syntax

![image](https://cloud.githubusercontent.com/assets/5100735/26820615/fcf29a80-4ad5-11e7-9fcd-19fe92c1b4d9.png)

**Comment by jeremydouglass** [comment]
Excellent.

Are the image assets being taken from the original Processing(Java) reference site, or are we generating the images from our reference sketches?

**Comment by gaocegege** [comment]
We will generate the image by

```r
# Original example code
saveFrame(''docs/img/arc1.png')
exit()
```

**Comment by jeremydouglass** [comment]
Very fun. Reference materials and e2e test -- I'm excited!
