### ISSUE TITLE
static function is not found in RLangPApplet instance in renjin

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#97]
radians is a function in PApplet, I am not sure why it raises an error with #95 

```
Instance of class rprocessing.RLangPApplet has no member named 'radians'
```

It fails examples/Basics/Trigonometry

**Comment by gaocegege** [comment]
I have found the cause, we will meet the problem when radians, ceil and so on is called.

It seems that renjin couldn't handle the static function well. `processing$radians(...)` works, but

```R
radians = processing$radians
radians(...)
```

will return `Instance of class rprocessing.RLangPApplet has no member named 'radians'`

And

```R
import(rprocessing.RLangPApplet)
radians = RLangPApplet$radians
radians(...)
```

works well.

**Comment by gaocegege** [comment]
ref https://github.com/bedatadriven/renjin/issues/320

**Comment by jeremydouglass** [comment]
Good investigation, and a clear bug report to renjin.

They have been very responsive and supportive so far. Let's see what effort level it would take for renjin to add static variable support, and what kind of priority they can make it.

**Comment by gaocegege** [comment]
Thank :smile: 

We have two options, actually:

1. Wait until there is a PR to fix the problem, or file a PR to renjin and fix the problem on our own. Then we could wrap these static functions by `xxx = processing$xxx`
1. Use `xxx = RLangPApplet$xxx` instead

And I think we could put the issue to low priority since there is only one function used in the examples. If the issue will be there for a long time, then we could use the latter way to avoid it.

**Comment by jeremydouglass** [comment]
Great. Then let's set this as low priority since there is a workaround.

As we get more coverage of the API we will know how many static functions
will be affected by this issue and we can reevaluate.

**Comment by gaocegege** [comment]
Done by some tricks in core.R #134

**Comment by jeremydouglass** [comment]
Sounds good. Static functions are implemented with the workaround -- but if renjin adds core support for static functions then we can incorporate that.

**Comment by jeremydouglass** [comment]
> 2. Use `xxx = RLangPApplet$xxx` instead
> [...] If the issue will be there for a long time, then we could use the latter way to avoid it.

I've asked a follow-up on this feature for renjin, but I think I will go ahead with option 2 for the next release so that we fix the bug / add the feature. We can change the implementation later if renjin changes.

**Comment by gaocegege** [comment]
SGTM
