### ISSUE TITLE
Support built-in variables

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#98]
There are some built-in variables such as height, width and frameCount, some works and others don't work, now.

Screen

- [x] <a href="https://processing.org/reference/height.html" class=" ref-link">height</a>
- [x] <a href="https://processing.org/reference/width.html" class=" ref-link">width</a>
- [x] <a href="https://processing.org/reference/pixelHeight.html" class=" ref-link">pixelHeight</a>
- [x] <a href="https://processing.org/reference/pixelWidth.html" class=" ref-link">pixelWidth</a>

Time

- [x] <a href="https://processing.org/reference/frameCount.html" class=" ref-link">frameCount</a>
- [x] <a href="https://processing.org/reference/frameRate.html" class=" ref-link">frameRate</a>
- [x] looping

Geometry

- [x] <a href="https://processing.org/reference/HALF_PI.html" class=" ref-link">HALF_PI</a>
- [x] <a href="https://processing.org/reference/PI.html" class=" ref-link">PI</a>
- [x] <a href="https://processing.org/reference/QUARTER_PI.html" class=" ref-link">QUARTER_PI</a>
- [x] <a href="https://processing.org/reference/TWO_PI.html" class=" ref-link">TWO_PI</a>
- [x] <a href="https://processing.org/reference/TAU.html" class=" ref-link">TAU</a>

Interaction

- [x] <a href="https://processing.org/reference/focused.html" class=" ref-link">focused</a>
- [x] <a href="https://processing.org/reference/key.html" class=" ref-link">key</a>
- [x] <a href="https://processing.org/reference/keyCode.html" class=" ref-link">keyCode</a>
- [x] <a href="https://processing.org/reference/mouseX.html" class=" ref-link">mouseX</a>
- [x] <a href="https://processing.org/reference/mouseY.html" class=" ref-link">mouseY</a>
- [x] <a href="https://processing.org/reference/pmouseX.html" class=" ref-link">pmouseX</a>
- [x] <a href="https://processing.org/reference/pmouseY.html" class=" ref-link">pmouseY</a>
- [x] <a href="https://processing.org/reference/keyPressed.html" class=" ref-link">keyPressed</a>
- [x] <a href="https://processing.org/reference/mousePressed.html" class=" ref-link">mousePressed</a>

**Comment by jeremydouglass** [comment]
You mentioned that some variables work -- can you give an example of one that works? In my last round of tests none of them were working, but I might not be calling them correctly.

I would say this may be higher than p3 because the majority of all demo Processing sketches use the `width` and `height` variables.

**Comment by gaocegege** [comment]
For example:

```r
yPos <- 0

draw <- function() {
    background(as.integer(204))
    yPos <- yPos - 1
    if (yPos < 0) {
        yPos <- height
    }
    line(0, yPos, width, yPos)
}
```

I set it to p3 because `width` and `height` works well. Do you meet any error when using these two variables?

**Comment by jeremydouglass** [comment]
Got it. I see that you've now added width and height, so I'm catching up.

I've updated the checklist above for checking off specific things as they are resolved.

If it makes sense then break parts of the list off into other issues -- for example, if the interaction constants won't be implemented.

-  Note also the related frameCount issue: #81

**Comment by jeremydouglass** [comment]
For new contributors, it looks like exposing the `keyPressed` and `mousePressed` booleans are only things left in this issue.

-  https://processing.org/reference/keyPressed.html
-  https://processing.org/reference/mousePressed.html

**Comment by gaocegege** [comment]
Closed since it has been solved.

**Comment by jeremydouglass** [comment]
OK! -- Is the "keyPressed function vs keyPressed variable" aspect still open via #170?

**Comment by gaocegege** [comment]
Yeah, I haven't solved the issue.
