### ISSUE TITLE
Fail to run in macOS

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#99]
It may be caused by #95

**Comment by jeremydouglass** [comment]
I don'd understand the description of this open issue. 

*What* fails to run on macOS? The mode?

I'm pulling the latest mode from HEAD and it installs and runs in PDE just fine on macOS, so I can't reproduce that. Or is something in CI on the mac failing, or something with test generation or running?

**Comment by gaocegege** [comment]
I fail to run PDE with R mode in my MacBook, so I open this issue to record it. I will have a try

**Comment by jeremydouglass** [comment]
Interesting -- I'm running it fine on a recent MacBook Pro, 10.12.5 Sierra.

Definitely test against PDE 3.3.3 -- 3.3.4 has several major open issues: https://github.com/processing/processing/issues/5111

**Comment by gaocegege** [comment]
My fault. Close it.
